### ISSUE TITLE
which cpu and sd-card used?

### ISSUE THREAD

**Issue by jian-li** [nikisalli/nik-lidar#6]
Hello nik, thank you for your great project. I find it is very interesting, and want to make one. All was ok, but I can not find which specific cpu and sd-card is used in this project. Thank you for your reply:)

**Comment by nikisalli** [comment]
esp-wroom-32 is the microcontroller, any 2GB sd card should work

**Comment by jian-li** [comment]
thank you for your quick reply, there are esp-wroom 32: esp32 wroom 32d and esp32 wroom 32e, which one should I use? Thx

**Comment by nikisalli** [comment]
it is called exactly esp32-wroom-32

**Comment by jian-li** [comment]
thx, I make it. esp32-wroom-32e is ok!
